import { beforeEach, describe, expect, it, vi } from "vitest";
import client from "../../axios/request";
import { buildMriBookmark } from "../../utils/mriQuery";
import { buildMriMaterializationQuery } from "../../utils/mriMaterializationQuery";
import { compressBase64, decompress } from "../../utils/cohortUrlCodec";
import {
  createWizardBookmark,
  listPatientAnalyticsCohorts,
  materializeWizardBookmark,
  WizardCohortApiError,
} from "../wizardCohortApi";

vi.mock("../../axios/request", () => ({
  default: {
    get: vi.fn(),
    post: vi.fn(),
  },
}));

const mockedGet = vi.mocked(client.get);
const mockedPost = vi.mocked(client.post);

describe("Wizard cohort API", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("lists Patient Analytics cohorts with dataset context", async () => {
    const controller = new AbortController();
    const response = [{ bmkId: "bookmark-1" }];
    mockedGet.mockResolvedValue({ data: response });

    await expect(listPatientAnalyticsCohorts("dataset-1", controller.signal)).resolves.toEqual(response);
    expect(mockedGet).toHaveBeenCalledWith("/d2e/d2e-webapi/cohortdefinition", {
      params: { source: "pa" },
      headers: { datasetid: "dataset-1" },
      signal: controller.signal,
    });
  });

  it("rejects a malformed cohort-list response", async () => {
    mockedGet.mockResolvedValue({ data: { unexpected: true } });

    await expect(listPatientAnalyticsCohorts("dataset-1")).rejects.toMatchObject({
      name: "WizardCohortApiError",
      operation: "list-cohorts",
      code: "invalid-response",
    });
  });

  it("creates a private Wizard bookmark with existing endpoint fields", async () => {
    mockedPost.mockResolvedValue({ data: { status: "success", bmkId: "bookmark-1" } });
    const bookmark = buildMriBookmark([], {}, { configId: "pa-config", configVersion: "7" }, "dataset-1").bookmark;

    await expect(
      createWizardBookmark({
        datasetId: "dataset-1",
        bookmarkname: "wizards-1783670400000",
        bookmark,
        paConfigId: "pa-config",
        cdmConfigId: "cdm-config",
        cdmConfigVersion: "3",
      }),
    ).resolves.toEqual({ status: "success", bmkId: "bookmark-1" });

    expect(mockedPost).toHaveBeenCalledWith(
      "/d2e/analytics-svc/api/services/bookmark",
      {
        cmd: "insert",
        bookmarkname: "wizards-1783670400000",
        bookmark: JSON.stringify(bookmark),
        shareBookmark: false,
        paConfigId: "pa-config",
        cdmConfigId: "cdm-config",
        cdmConfigVersion: "3",
        datasetId: "dataset-1",
      },
      { headers: { datasetid: "dataset-1" } },
    );
  });

  it("rejects bookmark creation when the backend omits the bookmark id", async () => {
    mockedPost.mockResolvedValue({ data: { status: "success" } });
    const bookmark = buildMriBookmark([], {}, { configId: "pa-config", configVersion: "7" }, "dataset-1").bookmark;

    await expect(
      createWizardBookmark({
        datasetId: "dataset-1",
        bookmarkname: "wizards-1783670400000",
        bookmark,
        paConfigId: "pa-config",
        cdmConfigId: "cdm-config",
        cdmConfigVersion: "3",
      }),
    ).rejects.toMatchObject({ operation: "create-bookmark", code: "invalid-response" });
  });

  it("materializes a Wizard bookmark with the existing cohort payload", async () => {
    mockedPost.mockResolvedValue({
      data: { message: "Cohort successfully materialized", cohortDefinitionId: 42 },
    });
    const bookmark = buildMriBookmark([], {}, { configId: "pa-config", configVersion: "7" }, "dataset-1").bookmark;
    const mriQuery = buildMriMaterializationQuery(bookmark, "dataset-1");

    await expect(
      materializeWizardBookmark({
        datasetId: "dataset-1",
        bookmarkId: "bookmark-1",
        bookmarkName: "wizards-1783670400000",
        description: "Generated by Wizards",
        mriQuery,
      }),
    ).resolves.toEqual({ cohortDefinitionId: 42 });

    expect(mockedPost).toHaveBeenCalledWith(
      "/d2e/analytics-svc/api/services/cohort",
      {
        datasetId: "dataset-1",
        mriquery: compressBase64(mriQuery),
        name: "wizards-1783670400000",
        description: "Generated by Wizards",
        syntax: JSON.stringify({ datasetId: "dataset-1", bookmarkId: "bookmark-1" }),
      },
      { headers: { datasetid: "dataset-1" } },
    );
    const submittedPayload = mockedPost.mock.calls[0][1] as { mriquery: string };
    expect(decompress(submittedPayload.mriquery)).toEqual(mriQuery);
  });

  it("rejects materialization when the backend omits the cohort definition id", async () => {
    mockedPost.mockResolvedValue({ data: { message: "Cohort successfully materialized" } });
    const bookmark = buildMriBookmark([], {}, { configId: "pa-config", configVersion: "7" }, "dataset-1").bookmark;

    await expect(
      materializeWizardBookmark({
        datasetId: "dataset-1",
        bookmarkId: "bookmark-1",
        bookmarkName: "wizards-1783670400000",
        mriQuery: buildMriMaterializationQuery(bookmark, "dataset-1"),
      }),
    ).rejects.toMatchObject({ operation: "materialize-cohort", code: "invalid-response" });
  });

  it("rejects bookmark creation across datasets before making a request", async () => {
    const bookmark = buildMriBookmark([], {}, { configId: "pa-config", configVersion: "7" }, "dataset-2").bookmark;

    await expect(
      createWizardBookmark({
        datasetId: "dataset-1",
        bookmarkname: "wizards-1783670400000",
        bookmark,
        paConfigId: "pa-config",
        cdmConfigId: "cdm-config",
        cdmConfigVersion: "3",
      }),
    ).rejects.toMatchObject({ code: "invalid-input" });
    expect(mockedPost).not.toHaveBeenCalled();
  });

  it("wraps transport failures without exposing the backend body", async () => {
    mockedGet.mockRejectedValue({
      message: "sensitive backend detail",
      response: { status: 503, data: { message: "database unavailable" } },
    });

    let caught: unknown;
    try {
      await listPatientAnalyticsCohorts("dataset-1");
    } catch (error) {
      caught = error;
    }

    expect(caught).toBeInstanceOf(WizardCohortApiError);
    expect(caught).toMatchObject({
      operation: "list-cohorts",
      code: "request-failed",
      status: 503,
      message: "Unable to check previous Wizard analyses",
    });
    expect(String(caught)).not.toContain("database unavailable");
  });
});
