apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_HOST: "{{ .Values.global.secrets.POSTGRES_HOST | b64enc }}"
  POSTGRES_SUPERUSER: "{{ .Values.global.secrets.POSTGRES_SUPERUSER | b64enc }}"
  POSTGRES_SUPERUSER_PASSWORD: "{{ .Values.global.secrets.POSTGRES_SUPERUSER_PASSWORD | b64enc }}"
  POSTGRES_CONFIG_ADMIN_USER: "{{ .Values.global.secrets.POSTGRES_CONFIG_ADMIN_USER | b64enc }}"
  POSTGRES_CONFIG_ADMIN_PASSWORD: "{{ .Values.global.secrets.POSTGRES_CONFIG_ADMIN_PASSWORD | b64enc }}"
  POSTGRES_CONFIG_WRITE_USER: "{{ .Values.global.secrets.POSTGRES_CONFIG_WRITE_USER | b64enc }}"
  POSTGRES_CONFIG_WRITE_PASSWORD: "{{ .Values.global.secrets.POSTGRES_CONFIG_WRITE_PASSWORD | b64enc }}"
  POSTGRES_IDP_ADMIN_USER: "{{ .Values.global.secrets.POSTGRES_IDP_ADMIN_USER | b64enc }}"
  POSTGRES_IDP_ADMIN_PASSWORD: "{{ .Values.global.secrets.POSTGRES_IDP_ADMIN_PASSWORD | b64enc }}"
  TLS__INTERNAL__CA_CRT: "{{ .Values.global.secrets.TLS__INTERNAL__CA_CRT | b64enc }}"
  POSTGRES_CONFIG_DB: "{{ .Values.global.secrets.POSTGRES_CONFIG_DB | b64enc }}"
  TLS__INTERNAL__CRT: "{{ .Values.global.secrets.TLS__INTERNAL__CRT | b64enc }}"
  TLS__INTERNAL__KEY: "{{ .Values.global.secrets.TLS__INTERNAL__KEY | b64enc }}"
  LOGTO_API_M2M_CLIENT_ID: "{{ .Values.global.secrets.LOGTO_API_M2M_CLIENT_ID | b64enc }}"
  LOGTO_API_M2M_CLIENT_SECRET: "{{ .Values.global.secrets.LOGTO_API_M2M_CLIENT_SECRET | b64enc }}"
  LOGTO__APP_CLIENT_ID: "{{ .Values.global.secrets.LOGTO__APP_CLIENT_ID | b64enc }}"
  LOGTO__APP_CLIENT_SECRET: "{{ .Values.global.secrets.LOGTO__APP_CLIENT_SECRET | b64enc }}"
  LOGTO__SVC_CLIENT_ID: "{{ .Values.global.secrets.LOGTO__SVC_CLIENT_ID | b64enc }}"
  LOGTO__SVC_CLIENT_SECRET: "{{ .Values.global.secrets.LOGTO__SVC_CLIENT_SECRET | b64enc }}"
  LOGTO__DATA_CLIENT_ID: "{{ .Values.global.secrets.LOGTO__DATA_CLIENT_ID | b64enc }}"
  LOGTO__DATA_CLIENT_SECRET: "{{ .Values.global.secrets.LOGTO__DATA_CLIENT_SECRET | b64enc }}"
  ROOT__PKI__CA_CRT: "{{ .Values.secrets.ROOT__PKI__CA_CRT | b64enc }}"
  ROOT__PKI__CA_KEY: "{{ .Values.secrets.ROOT__PKI__CA_KEY | b64enc }}"
  IDP__JDBC__URL: "{{ printf "postgres://%s:%s@%s:5432/%s?sslmode=%s&options=-c search_path=logto" .Values.global.secrets.POSTGRES_IDP_ADMIN_USER .Values.global.secrets.POSTGRES_IDP_ADMIN_PASSWORD .Values.global.secrets.POSTGRES_HOST .Values.global.secrets.POSTGRES_CONFIG_DB .Values.global.pgSSLMode | b64enc }}"
  SUPABASE_STORAGE_JWT_SECRET: "{{ .Values.global.secrets.SUPABASE_STORAGE_JWT_SECRET | b64enc }}"
  SUPABASE_STORAGE_JWT_TOKEN: "{{ .Values.global.secrets.SUPABASE_STORAGE_JWT_TOKEN | b64enc }}"
---

apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-caddy"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ROOT__PKI__CA_CRT: "{{ .Values.secrets.ROOT__PKI__CA_CRT | b64enc }}"
  ROOT__PKI__CA_KEY: "{{ .Values.secrets.ROOT__PKI__CA_KEY | b64enc }}"
  SERVER__CRT: "{{ .Values.secrets.SERVER__CRT | b64enc }}"
  SERVER__KEY: "{{ .Values.secrets.SERVER__KEY | b64enc }}"