apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dataflow-gen-worker-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: worker
rules:
  - apiGroups: [""]
    resources: ["events", "pods", "pods/log", "pods/status"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dataflow-gen-worker-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: worker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dataflow-gen-worker-role
subjects:
  - kind: ServiceAccount
    name: dataflow-gen-svc-acc
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-viewer-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
# clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-viewer-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: pod-viewer
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: pod-viewer-role
  apiGroup: rbac.authorization.k8s.io