apiVersion: v1
kind: ServiceAccount
metadata:
  name: dataflow-gen-svc-acc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: worker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-viewer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: viewer
