name: d2e-services
description: A generated Helm Chart for deploy/k8s
version: 0.18.13-beta
appVersion: "0.18.8-beta"
apiVersion: v2
dependencies:
  - name: d2e-core
    version: 0.18.13
keywords:
  - deploy/k8s
